[package]
name = "jude_omenai"
version = "0.1.0"
authors = ["Jude <jdonmarie@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
regex = "1"
serde_json = "1.0.61"
serde = "1.0.119"